version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app/client"
    schedule:
      interval: "weekly"
    groups:
      client-patch:
        update-types:
          - "patch"

  - package-ecosystem: "npm"
    directory: "/app/server"
    schedule:
      interval: "weekly"
    groups:
      server-patch:
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
